imports:
  - php

filter:
  excluded_paths:
    - vendor/*
    - tests/*

build:
  image: default-bionic

  tests:
    override:
      - composer install
      - composer phpunit

  coverage:
    # Path to your coverage file (adjust if needed)
    file: docs/coverage.clover
    format: php-clover
