# .scrutinizer.yml

imports:
  - php

filter:
  excluded_paths:
    - vendor/*
    - tests/*

build:
  image: default-bionic

  # Define a single build node where tests run
  nodes:
    tests-node:
      environment:
        php:
          version: 8.3
      tests:
        override:
          - composer install
          - composer phpunit  # Or your custom phpunit command

analysis:
  # Tell Scrutinizer where to find the coverage report
  tests:
    override:
      - command: "composer phpunit"
        coverage:
          file: "docs/coverage.clover"
          format: "php-clover"
